version: '3'
services:

  wasp:
    image: iotaledger/wasp:${WASP_VERSION:?WASP_VERSION is missing}
    container_name: ${WASP_LEDGER_NETWORK:?WASP_LEDGER_NETWORK is missing}-wasp
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    stop_grace_period: 1m
    tty: true
    working_dir: /app
    user: "65532"
    ports:
      - "${WASP_PEERING_PORT:-4000}:${WASP_PEERING_PORT:-4000}/tcp"
      - "${WASP_PEERING_PORT:-4000}:${WASP_PEERING_PORT:-4000}/udp"
    labels:
      - "proxy.constraint=wasp"
      - "traefik.enable=true"

      - "traefik.http.services.webapi.loadbalancer.server.port=9090"
      - "traefik.http.services.webapi.loadbalancer.healthCheck.path=/health"
      - "traefik.http.services.webapi.loadbalancer.healthCheck.interval=10s"
      - "traefik.http.services.webapi.loadbalancer.healthCheck.timeout=3s"

      - "traefik.http.routers.webapi.service=webapi"
      - "traefik.http.routers.webapi.rule=Host(`${WASP_HOST:?WASP_HOST is missing}`)"
      - "traefik.http.routers.webapi.entrypoints=webapisecure"
      - "traefik.http.routers.webapi.tls=true"
      - "traefik.http.routers.webapi.tls.certresolver=myresolver"
    entrypoint:
      - "/app/wasp"
    command:
      - "-c"
      - "/etc/wasp_config.json"
      - "-u"
      - "/etc/wasp_users.json"
    cap_drop:
      - ALL
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${WASP_DATA_DIR:-./data}/waspdb:/app/waspdb"
      - "${WASP_DATA_DIR:-./data}/config/config.json:/etc/wasp_config.json:ro"
      - "${WASP_DATA_DIR:-./data}/config/users.json:/etc/wasp_users.json:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  wasp-dashboard:
    image: iotaledger/wasp-dashboard:${WASP_DASHBOARD_VERSION:?WASP_DASHBOARD_VERSION is missing}
    container_name: ${WASP_LEDGER_NETWORK:?WASP_LEDGER_NETWORK is missing}-wasp.dashboard
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      wasp:
        condition: service_started
    labels:
      - "proxy.constraint=wasp"
      - "traefik.enable=true"

      - "traefik.http.services.dashboard.loadbalancer.server.port=80"

      # redirect requests to '/' to '/wasp/dashboard'
      - "traefik.http.routers.dashboard-redirect.service=dashboard"
      - "traefik.http.routers.dashboard-redirect.rule=Host(`${WASP_HOST:?WASP_HOST is missing}`) && Path(`/`)"
      - "traefik.http.routers.dashboard-redirect.entrypoints=websecure"
      - "traefik.http.routers.dashboard-redirect.tls=true"
      - "traefik.http.routers.dashboard-redirect.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard-redirect.middlewares=dashboard-redirect"
      - "traefik.http.middlewares.dashboard-redirect.redirectregex.regex=.*"
      - "traefik.http.middlewares.dashboard-redirect.redirectregex.replacement=https://${WASP_HOST:?WASP_HOST is missing}:${WASP_HTTPS_PORT:-447}/wasp/dashboard"

      # handle requests to '/wasp/dashboard'
      - "traefik.http.routers.dashboard.service=dashboard"
      - "traefik.http.routers.dashboard.rule=Host(`${WASP_HOST:?WASP_HOST is missing}`) && (Path(`/wasp/dashboard`) || PathPrefix(`/wasp/dashboard/`))"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=rewrite-wasp-dashboard,cors-headers"
      - "traefik.http.middlewares.rewrite-wasp-dashboard.stripprefix.prefixes=/wasp/dashboard"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=https://${WASP_HOST:?WASP_HOST is missing}:${WASP_API_PORT:-448}"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"
    environment:
      - WASP_API_URL=https://${WASP_HOST:?WASP_HOST is missing}:${WASP_API_PORT:-448}
      - L1_API_URL=http://hornet:9029
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  ##################################################################
  #  Reverse Proxy and SSL                                         #
  ##################################################################

  traefik:
    image: traefik:v2.8.2
    container_name: ${WASP_LEDGER_NETWORK:?WASP_LEDGER_NETWORK is missing}-wasp.traefik
    restart: unless-stopped
    env_file:
      - .env
    command:
      - "--log.level=WARN"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`proxy.constraint`,`wasp`)"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=10"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=10"
      - "--entrypoints.webapisecure.address=:448"

      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${WASP_HTTP_PORT:-80}:80/tcp"
      - "${WASP_HTTPS_PORT:-443}:443/tcp"
      - "${WASP_API_PORT:-448}:448/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${WASP_DATA_DIR:-./data}/letsencrypt:/letsencrypt"
      - "./assets/traefik:/etc/traefik/dynamic:ro"
      - "${WASP_SSL_CERT:-./assets/traefik/certs/fake.cert}:/certs/domain.cert:ro"
      - "${WASP_SSL_KEY:-./assets/traefik/certs/fake.key}:/certs/domain.key:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

networks:
  default:
    name: ${WASP_LEDGER_NETWORK}
    external: true
